-- MySQL Script generated by MySQL Workbench
-- qui 07 nov 2024 05:57:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pbavaliacoes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pbavaliacoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pbavaliacoes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `pbavaliacoes` ;

-- -----------------------------------------------------
-- Table `pbavaliacoes`.`business_unities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pbavaliacoes`.`business_unities` (
  `id_bu` INT NOT NULL,
  `nome_bu` VARCHAR(100) NOT NULL,
  `csat_bu` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_bu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_business_unities_csat_bu` ON `pbavaliacoes`.`business_unities` (`csat_bu` ASC) VISIBLE;

CREATE INDEX `idx_business_unities_nome_bu` ON `pbavaliacoes`.`business_unities` (`nome_bu` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pbavaliacoes`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pbavaliacoes`.`projetos` (
  `id_projeto` INT NOT NULL,
  `nome_projeto` VARCHAR(100) NOT NULL,
  `csat_projeto` DECIMAL(5,2) NULL DEFAULT NULL,
  `id_bu` INT NOT NULL,
  PRIMARY KEY (`id_projeto`),
  CONSTRAINT `fk_projetos_id_bu`
    FOREIGN KEY (`id_bu`)
    REFERENCES `pbavaliacoes`.`business_unities` (`id_bu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_projetos_id_bu` ON `pbavaliacoes`.`projetos` (`id_bu` ASC) VISIBLE;

CREATE INDEX `idx_projetos_csat_projeto` ON `pbavaliacoes`.`projetos` (`csat_projeto` ASC) VISIBLE;

CREATE INDEX `idx_projetos_idbu_idprojeto` ON `pbavaliacoes`.`projetos` (`id_bu` ASC, `id_projeto` ASC) VISIBLE;

CREATE INDEX `idx_projetos_nome_projeto` ON `pbavaliacoes`.`projetos` (`nome_projeto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pbavaliacoes`.`checklists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pbavaliacoes`.`checklists` (
  `id_checklist` INT NOT NULL,
  `nome_checklist` VARCHAR(100) NOT NULL,
  `id_projeto` INT NOT NULL,
  `csat_checklist` DECIMAL(5,2) NULL DEFAULT NULL,
  `total_entregaveis` INT NULL DEFAULT '0',
  PRIMARY KEY (`id_checklist`),
  CONSTRAINT `checklists_ibfk_1`
    FOREIGN KEY (`id_projeto`)
    REFERENCES `pbavaliacoes`.`projetos` (`id_projeto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_checklists_projeto` ON `pbavaliacoes`.`checklists` (`id_projeto` ASC) VISIBLE;

CREATE INDEX `idx_checklists_csat_checklist` ON `pbavaliacoes`.`checklists` (`csat_checklist` ASC) VISIBLE;

CREATE INDEX `idx_checklists_idprojeto_idchecklist` ON `pbavaliacoes`.`checklists` (`id_projeto` ASC, `id_checklist` ASC) VISIBLE;

CREATE INDEX `idx_checklists_nome_checklist` ON `pbavaliacoes`.`checklists` (`nome_checklist` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pbavaliacoes`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pbavaliacoes`.`avaliacoes` (
  `id_avaliacao` INT NOT NULL,
  `id_checklist` INT NOT NULL,
  `data_avaliacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo_avaliacao` VARCHAR(50) NOT NULL,
  `csat_avaliacao` DECIMAL(5,2) NULL DEFAULT NULL,
  `total_entregaveis` INT NULL DEFAULT '0',
  `total_participantes` INT NULL DEFAULT '0',
  `status` ENUM('Backlog', 'Em andamento', 'Encerrada') NULL DEFAULT 'Backlog',
  `csat_conteudo` DECIMAL(5,2) NULL DEFAULT NULL,
  `csat_consultor` DECIMAL(5,2) NULL DEFAULT NULL,
  `csat_evento` DECIMAL(5,2) NULL DEFAULT NULL,
  `nps_avaliacao` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id_avaliacao`),
  CONSTRAINT `avaliacoes_ibfk_1`
    FOREIGN KEY (`id_checklist`)
    REFERENCES `pbavaliacoes`.`checklists` (`id_checklist`),
  CONSTRAINT `avaliacoes_ibfk_2`
    FOREIGN KEY (`id_checklist`)
    REFERENCES `pbavaliacoes`.`checklists` (`id_checklist`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_avaliacoes_checklist` ON `pbavaliacoes`.`avaliacoes` (`id_checklist` ASC) VISIBLE;

CREATE INDEX `idx_avaliacoes_status` ON `pbavaliacoes`.`avaliacoes` (`status` ASC) VISIBLE;

CREATE INDEX `idx_avaliacoes_csat_avaliacao` ON `pbavaliacoes`.`avaliacoes` (`csat_avaliacao` ASC) VISIBLE;

CREATE INDEX `idx_avaliacoes_idchecklist_idavaliacao` ON `pbavaliacoes`.`avaliacoes` (`id_checklist` ASC, `id_avaliacao` ASC) VISIBLE;

CREATE INDEX `idx_avaliacoes_nps_avaliacao` ON `pbavaliacoes`.`avaliacoes` (`nps_avaliacao` ASC) VISIBLE;

CREATE INDEX `idx_avaliacoes_csat_conteudo` ON `pbavaliacoes`.`avaliacoes` (`csat_conteudo` ASC) VISIBLE;

CREATE INDEX `idx_avaliacoes_csat_evento` ON `pbavaliacoes`.`avaliacoes` (`csat_evento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pbavaliacoes`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pbavaliacoes`.`clientes` (
  `id_cliente` INT NOT NULL,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `id_bu` INT NOT NULL,
  `csat_cliente` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `clientes_ibfk_1`
    FOREIGN KEY (`id_bu`)
    REFERENCES `pbavaliacoes`.`business_unities` (`id_bu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_clientes_csat_cliente` ON `pbavaliacoes`.`clientes` (`csat_cliente` ASC) VISIBLE;

CREATE INDEX `idx_clientes_id_bu` ON `pbavaliacoes`.`clientes` (`id_bu` ASC) VISIBLE;

CREATE INDEX `idx_clientes_nome_cliente` ON `pbavaliacoes`.`clientes` (`nome_cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pbavaliacoes`.`clientes_projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pbavaliacoes`.`clientes_projetos` (
  `id_cliente` INT NOT NULL,
  `id_projeto` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `id_projeto`),
  CONSTRAINT `clientes_projetos_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `pbavaliacoes`.`clientes` (`id_cliente`),
  CONSTRAINT `clientes_projetos_ibfk_2`
    FOREIGN KEY (`id_projeto`)
    REFERENCES `pbavaliacoes`.`projetos` (`id_projeto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_clientes_projetos_idcliente_idprojeto` ON `pbavaliacoes`.`clientes_projetos` (`id_cliente` ASC, `id_projeto` ASC) VISIBLE;

CREATE INDEX `idx_clientes_projetos_cliente` ON `pbavaliacoes`.`clientes_projetos` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `idx_clientes_projetos_projeto` ON `pbavaliacoes`.`clientes_projetos` (`id_projeto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pbavaliacoes`.`entregaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pbavaliacoes`.`entregaveis` (
  `id_entregavel` VARCHAR(255) NOT NULL,
  `id_avaliacao` INT NOT NULL,
  `data_recebimento` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `csat_entregavel` DECIMAL(5,2) NULL DEFAULT NULL,
  `id_typeform` VARCHAR(50) NULL DEFAULT NULL,
  `nome_respondente` VARCHAR(100) NULL DEFAULT NULL,
  `nps` DECIMAL(5,2) NOT NULL,
  `csat_conteudo` DECIMAL(5,2) NULL DEFAULT NULL,
  `csat_consultor` DECIMAL(5,2) NULL DEFAULT NULL,
  `csat_evento` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_entregavel`),
  CONSTRAINT `entregaveis_ibfk_1`
    FOREIGN KEY (`id_avaliacao`)
    REFERENCES `pbavaliacoes`.`avaliacoes` (`id_avaliacao`),
  CONSTRAINT `entregaveis_ibfk_2`
    FOREIGN KEY (`id_avaliacao`)
    REFERENCES `pbavaliacoes`.`avaliacoes` (`id_avaliacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_entregaveis_idavaliacao_identregavel` ON `pbavaliacoes`.`entregaveis` (`id_avaliacao` ASC, `id_entregavel` ASC) VISIBLE;

CREATE INDEX `idx_entregaveis_nps` ON `pbavaliacoes`.`entregaveis` (`nps` ASC) VISIBLE;

CREATE INDEX `idx_entregaveis_csat_conteudo` ON `pbavaliacoes`.`entregaveis` (`csat_conteudo` ASC) VISIBLE;

CREATE INDEX `idx_entregaveis_csat_evento` ON `pbavaliacoes`.`entregaveis` (`csat_evento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pbavaliacoes`.`perguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pbavaliacoes`.`perguntas` (
  `id_pergunta` VARCHAR(50) NOT NULL,
  `id_avaliacao` INT NOT NULL,
  `texto_pergunta` VARCHAR(255) NOT NULL,
  `tipo_pergunta` VARCHAR(50) NOT NULL,
  `ordem` INT NOT NULL,
  `opcional` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_pergunta`, `id_avaliacao`),
  CONSTRAINT `perguntas_ibfk_1`
    FOREIGN KEY (`id_avaliacao`)
    REFERENCES `pbavaliacoes`.`avaliacoes` (`id_avaliacao`),
  CONSTRAINT `perguntas_ibfk_2`
    FOREIGN KEY (`id_avaliacao`)
    REFERENCES `pbavaliacoes`.`avaliacoes` (`id_avaliacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_perguntas_avaliacao` ON `pbavaliacoes`.`perguntas` (`id_avaliacao` ASC) VISIBLE;

CREATE INDEX `idx_perguntas_idavaliacao_idpergunta` ON `pbavaliacoes`.`perguntas` (`id_avaliacao` ASC, `id_pergunta` ASC) VISIBLE;

CREATE INDEX `idx_perguntas_tipo_pergunta` ON `pbavaliacoes`.`perguntas` (`tipo_pergunta` ASC) VISIBLE;

CREATE INDEX `idx_perguntas_tipo_id` ON `pbavaliacoes`.`perguntas` (`tipo_pergunta` ASC, `id_pergunta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pbavaliacoes`.`respostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pbavaliacoes`.`respostas` (
  `id_resposta` INT NOT NULL AUTO_INCREMENT,
  `id_entregavel` VARCHAR(255) NOT NULL,
  `id_pergunta` VARCHAR(50) NOT NULL,
  `id_avaliacao` INT NOT NULL,
  `valor_resposta` DECIMAL(5,2) NULL DEFAULT NULL,
  `texto_resposta` VARCHAR(500) NULL DEFAULT NULL,
  `tipo_resposta` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_resposta`),
  CONSTRAINT `respostas_ibfk_1`
    FOREIGN KEY (`id_entregavel`)
    REFERENCES `pbavaliacoes`.`entregaveis` (`id_entregavel`),
  CONSTRAINT `respostas_ibfk_2`
    FOREIGN KEY (`id_pergunta` , `id_avaliacao`)
    REFERENCES `pbavaliacoes`.`perguntas` (`id_pergunta` , `id_avaliacao`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_respostas_entregavel` ON `pbavaliacoes`.`respostas` (`id_entregavel` ASC) VISIBLE;

CREATE INDEX `idx_respostas_pergunta` ON `pbavaliacoes`.`respostas` (`id_pergunta` ASC) VISIBLE;

CREATE INDEX `idx_respostas_pergunta_avaliacao` ON `pbavaliacoes`.`respostas` (`id_pergunta` ASC, `id_avaliacao` ASC) VISIBLE;

CREATE INDEX `idx_respostas_idavaliacao_idpergunta` ON `pbavaliacoes`.`respostas` (`id_avaliacao` ASC, `id_pergunta` ASC) VISIBLE;

CREATE INDEX `idx_respostas_identregavel_idpergunta` ON `pbavaliacoes`.`respostas` (`id_entregavel` ASC, `id_pergunta` ASC) VISIBLE;

CREATE INDEX `idx_respostas_idavaliacao_identregavel` ON `pbavaliacoes`.`respostas` (`id_avaliacao` ASC, `id_entregavel` ASC) VISIBLE;

CREATE INDEX `idx_respostas_valor_resposta` ON `pbavaliacoes`.`respostas` (`valor_resposta` ASC) VISIBLE;

CREATE INDEX `idx_respostas_tipo_resposta` ON `pbavaliacoes`.`respostas` (`tipo_resposta` ASC) VISIBLE;

CREATE INDEX `idx_respostas_tipo_valor` ON `pbavaliacoes`.`respostas` (`tipo_resposta` ASC, `valor_resposta` ASC) VISIBLE;

CREATE FULLTEXT INDEX `idx_respostas_texto_resposta` ON `pbavaliacoes`.`respostas` (`texto_resposta`) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
